### ISSUE TITLE
correccion 20/9

### ISSUE THREAD

**Issue by Fvazquez-pioix** [PioIX/2024---TPconsola---G16#1]
Falta la segunda parte de la consigna que se agrego el 23/8

Faltaria agregar ejemplos de codigo con formato de caja de codigo o los ejemplos que estan darles formato de caja de codigo y mostrar el resultado con una imagen de la consola.

[formato de caja o bloque de codigo](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
[imagenes](https://denshub.com/es/hugo-post-insert-image/)
recordar que las imagenes se deben guardar en el repositorio y no usar imagenes hosteadas en la web

**Comment by Joaquin-Colodro** [comment]
agregamos el formato de código y una foto con los ejemplos por consola
